# Generated by Django 6.0 on 2026-01-29 05:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('video_url', models.URLField(verbose_name='Video URL')),
                ('video_type', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('facebook', 'Facebook'), ('virtual_tour', 'Virtual Tour'), ('property_video', 'Property Video')], max_length=20, verbose_name='Video Type')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='properties/videos/thumbnails/', verbose_name='Thumbnail')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Property Video',
                'verbose_name_plural': 'Property Videos',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['category', 'display_order', 'name'], 'verbose_name': 'Amenity', 'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertycategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Property Category', 'verbose_name_plural': 'Property Categories'},
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['order', 'uploaded_at'], 'verbose_name': 'Property Image', 'verbose_name_plural': 'Property Images'},
        ),
        migrations.AlterModelOptions(
            name='propertysubcategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Property Subcategory', 'verbose_name_plural': 'Property Subcategories'},
        ),
        migrations.RemoveIndex(
            model_name='amenity',
            name='core_amenit_slug_e4e13e_idx',
        ),
        migrations.RemoveIndex(
            model_name='amenity',
            name='core_amenit_categor_66941d_idx',
        ),
        migrations.RemoveIndex(
            model_name='amenity',
            name='core_amenit_is_acti_68c54b_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='core_proper_area_cb66d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='core_proper_is_feat_09dca4_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='core_proper_is_acti_87ea35_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='core_proper_is_veri_ade3f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='core_proper_status_95c99c_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='core_proper_owner_i_a5a8dd_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='core_proper_latitud_67d4ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='core_proper_expires_0e6286_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='core_proper_perform_8e6a29_idx',
        ),
        migrations.RemoveIndex(
            model_name='propertycategory',
            name='core_proper_slug_dca176_idx',
        ),
        migrations.RemoveIndex(
            model_name='propertycategory',
            name='core_proper_propert_fbddb3_idx',
        ),
        migrations.RemoveIndex(
            model_name='propertycategory',
            name='core_proper_is_acti_99410d_idx',
        ),
        migrations.RemoveIndex(
            model_name='propertyimage',
            name='core_proper_propert_ef7ca8_idx',
        ),
        migrations.RemoveIndex(
            model_name='propertyimage',
            name='core_proper_propert_79dbbf_idx',
        ),
        migrations.RemoveIndex(
            model_name='propertyinquiry',
            name='core_proper_is_read_816c91_idx',
        ),
        migrations.RemoveIndex(
            model_name='propertyinquiry',
            name='core_proper_status_695756_idx',
        ),
        migrations.RenameField(
            model_name='propertyinquiry',
            old_name='guest_email',
            new_name='email',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='estate_app__slug_3e42f9_idx',
            old_name='core_proper_slug_b23ff2_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='estate_app__city_e68331_idx',
            old_name='core_proper_city_984059_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='estate_app__price_a59990_idx',
            old_name='core_proper_price_652b7d_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='estate_app__bedroom_509919_idx',
            old_name='core_proper_bedroom_cf366a_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='estate_app__created_9e6922_idx',
            old_name='core_proper_created_a942a9_idx',
        ),
        migrations.AlterUniqueTogether(
            name='propertyimage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='amenity',
            name='applicable_to',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('land', 'Plots/Land'), ('agricultural', 'Agricultural'), ('pg_co-living', 'PG/Co-Living')], default='residential', max_length=20, verbose_name='Applicable To'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AddField(
            model_name='property',
            name='age_of_property',
            field=models.CharField(blank=True, choices=[('new', 'New Construction'), ('under_construction', 'Under Construction'), ('0-1', 'Less than 1 year'), ('1-5', '1-5 years'), ('5-10', '5-10 years'), ('10+', 'More than 10 years')], max_length=20, null=True, verbose_name='Age of Property'),
        ),
        migrations.AddField(
            model_name='property',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Alternate Phone'),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', to='estate_app.amenity'),
        ),
        migrations.AddField(
            model_name='property',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='property',
            name='available_from',
            field=models.DateField(blank=True, null=True, verbose_name='Available From'),
        ),
        migrations.AddField(
            model_name='property',
            name='booking_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Booking Amount'),
        ),
        migrations.AddField(
            model_name='property',
            name='carpet_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Carpet Area'),
        ),
        migrations.AddField(
            model_name='property',
            name='clear_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Clear Height (ft)'),
        ),
        migrations.AddField(
            model_name='property',
            name='click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Click Count'),
        ),
        migrations.AddField(
            model_name='property',
            name='conference_room',
            field=models.BooleanField(default=False, verbose_name='Conference Room Available'),
        ),
        migrations.AddField(
            model_name='property',
            name='crops_grown',
            field=models.TextField(blank=True, null=True, verbose_name='Crops Grown'),
        ),
        migrations.AddField(
            model_name='property',
            name='electricity_connection',
            field=models.BooleanField(default=False, verbose_name='Electricity Connection'),
        ),
        migrations.AddField(
            model_name='property',
            name='facing',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('north_east', 'North-East'), ('north_west', 'North-West'), ('south_east', 'South-East'), ('south_west', 'South-West')], max_length=20, null=True, verbose_name='Facing Direction'),
        ),
        migrations.AddField(
            model_name='property',
            name='facing_road_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Facing Road Width (ft)'),
        ),
        migrations.AddField(
            model_name='property',
            name='farm_house',
            field=models.BooleanField(default=False, verbose_name='Farm House Available'),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_loading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Floor Loading (kg/sqft)'),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Floor Number'),
        ),
        migrations.AddField(
            model_name='property',
            name='food_included',
            field=models.BooleanField(default=False, verbose_name='Food Included'),
        ),
        migrations.AddField(
            model_name='property',
            name='irrigation_facilities',
            field=models.TextField(blank=True, null=True, verbose_name='Irrigation Facilities'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Urgent'),
        ),
        migrations.AddField(
            model_name='property',
            name='laundry_service',
            field=models.BooleanField(default=False, verbose_name='Laundry Service'),
        ),
        migrations.AddField(
            model_name='property',
            name='legal_documents',
            field=models.TextField(blank=True, null=True, verbose_name='Legal Documents'),
        ),
        migrations.AddField(
            model_name='property',
            name='maintenance_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maintenance Charges'),
        ),
        migrations.AddField(
            model_name='property',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold'), ('cooperative', 'Cooperative Society'), ('power_of_attorney', 'Power of Attorney')], max_length=20, null=True, verbose_name='Ownership Type'),
        ),
        migrations.AddField(
            model_name='property',
            name='pantry',
            field=models.BooleanField(default=False, verbose_name='Pantry Available'),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Plot Area'),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_breadth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Plot Breadth'),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Plot Length'),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_type',
            field=models.CharField(blank=True, choices=[('corner', 'Corner Plot'), ('inside', 'Inside Plot'), ('park_facing', 'Park Facing'), ('road_facing', 'Main Road Facing')], max_length=20, null=True, verbose_name='Plot Type'),
        ),
        migrations.AddField(
            model_name='property',
            name='possession_status',
            field=models.CharField(blank=True, choices=[('ready_to_move', 'Ready to Move'), ('under_construction', 'Under Construction'), ('resale', 'Resale'), ('new_booking', 'New Booking')], max_length=20, null=True, verbose_name='Possession Status'),
        ),
        migrations.AddField(
            model_name='property',
            name='power_backup',
            field=models.CharField(blank=True, choices=[('inverter', 'Inverter'), ('dg_set', 'DG Set'), ('both', 'Both'), ('none', 'None')], max_length=10, null=True, verbose_name='Power Backup'),
        ),
        migrations.AddField(
            model_name='property',
            name='preferred_contact_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Preferred Contact Time'),
        ),
        migrations.AddField(
            model_name='property',
            name='preferred_tenants',
            field=models.CharField(blank=True, choices=[('family', 'Family Only'), ('bachelors', 'Bachelors Allowed'), ('company', 'Company Lease'), ('anyone', 'Anyone')], max_length=20, null=True, verbose_name='Preferred Tenants'),
        ),
        migrations.AddField(
            model_name='property',
            name='separate_washrooms',
            field=models.BooleanField(default=False, verbose_name='Separate Washrooms'),
        ),
        migrations.AddField(
            model_name='property',
            name='shared_rooms',
            field=models.BooleanField(default=False, verbose_name='Shared Rooms Available'),
        ),
        migrations.AddField(
            model_name='property',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('black', 'Black Soil'), ('red', 'Red Soil'), ('laterite', 'Laterite Soil'), ('alluvial', 'Alluvial Soil'), ('mountain', 'Mountain Soil'), ('desert', 'Desert Soil')], max_length=20, null=True, verbose_name='Soil Type'),
        ),
        migrations.AddField(
            model_name='property',
            name='super_area',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Super/Built-up Area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Floors'),
        ),
        migrations.AddField(
            model_name='property',
            name='washrooms',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='Washrooms'),
        ),
        migrations.AddField(
            model_name='property',
            name='water_source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Water Source'),
        ),
        migrations.AddField(
            model_name='property',
            name='whatsapp_enabled',
            field=models.BooleanField(default=True, verbose_name='WhatsApp Enabled'),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='has_age',
            field=models.BooleanField(default=False, verbose_name='Has Age'),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='has_area',
            field=models.BooleanField(default=True, verbose_name='Has Area'),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='has_balconies',
            field=models.BooleanField(default=False, verbose_name='Has Balconies'),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='has_bathrooms',
            field=models.BooleanField(default=False, verbose_name='Has Bathrooms'),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='has_bedrooms',
            field=models.BooleanField(default=False, verbose_name='Has Bedrooms'),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='has_clear_height',
            field=models.BooleanField(default=False, verbose_name='Has Clear Height'),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='has_conference_room',
            field=models.BooleanField(default=False, verbose_name='Has Conference Room'),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='has_crops',
            field=models.BooleanField(default=False, verbose_name='Has Crops'),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='has_dimensions',
            field=models.BooleanField(default=False, verbose_name='Has Dimensions'),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='has_facing',
            field=models.BooleanField(default=False, verbose_name='Has Facing'),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='has_floor',
            field=models.BooleanField(default=False, verbose_name='Has Floor Number'),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='has_floor_loading',
            field=models.BooleanField(default=False, verbose_name='Has Floor Loading'),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='has_furnishing',
            field=models.BooleanField(default=False, verbose_name='Has Furnishing'),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='has_irrigation',
            field=models.BooleanField(default=False, verbose_name='Has Irrigation'),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='has_pantry',
            field=models.BooleanField(default=False, verbose_name='Has Pantry'),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='has_parking',
            field=models.BooleanField(default=True, verbose_name='Has Parking'),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='has_power_backup',
            field=models.BooleanField(default=False, verbose_name='Has Power Backup'),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='has_soil_type',
            field=models.BooleanField(default=False, verbose_name='Has Soil Type'),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='has_washrooms',
            field=models.BooleanField(default=False, verbose_name='Has Washrooms'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='budget'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='consent_given',
            field=models.BooleanField(default=True, verbose_name='consent given'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='contact_method',
            field=models.CharField(choices=[('phone', 'Phone Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS'), ('form', 'Contact Form')], default='form', max_length=20, verbose_name='contact method'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='last_contacted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last contacted'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='lead_source',
            field=models.CharField(choices=[('website', 'Website'), ('mobile_app', 'Mobile App'), ('partner', 'Partner Site'), ('referral', 'Referral'), ('organic', 'Organic Search')], default='website', max_length=20, verbose_name='lead source'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='name',
            field=models.CharField(default=2, max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('hot', 'Hot')], default='medium', max_length=20, verbose_name='priority'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='timeline',
            field=models.CharField(blank=True, help_text='When do they plan to buy/rent?', max_length=50, null=True, verbose_name='timeline'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='whatsapp_enabled',
            field=models.BooleanField(default=True, verbose_name='whatsapp enabled'),
        ),
        migrations.AddField(
            model_name='propertysubcategory',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AddField(
            model_name='propertysubcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agency_name',
            field=models.CharField(blank=True, help_text='Real estate agency name (required for sellers and agents)', max_length=255, null=True, verbose_name='agency name'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='category',
            field=models.CharField(choices=[('basic', 'Basic Amenities'), ('security', 'Security'), ('parking', 'Parking'), ('community', 'Community'), ('green', 'Green Features'), ('luxury', 'Luxury Amenities'), ('commercial', 'Commercial'), ('agricultural', 'Agricultural')], default='basic', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='description',
            field=models.TextField(blank=True, default=3, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.CharField(blank=True, default=4, max_length=50, verbose_name='Icon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amenity',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Amenity Name'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area_unit',
            field=models.CharField(choices=[('sqft', 'Square Feet'), ('sqm', 'Square Meters'), ('sqyd', 'Square Yards'), ('acre', 'Acres'), ('hectare', 'Hectares'), ('gunta', 'Guntas'), ('marla', 'Marla'), ('bigha', 'Bigha')], default='sqft', max_length=10, verbose_name='Area Unit'),
        ),
        migrations.AlterField(
            model_name='property',
            name='balconies',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Balconies'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='Bathrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='Bedrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='estate_app.propertycategory'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(db_index=True, max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='property',
            name='contact_email',
            field=models.EmailField(default=4, max_length=254, verbose_name='Contact Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='contact_person',
            field=models.CharField(default=2, max_length=100, verbose_name='Contact Person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='contact_phone',
            field=models.CharField(default=2, max_length=15, verbose_name='Contact Phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(default='India', max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Featured Until'),
        ),
        migrations.AlterField(
            model_name='property',
            name='furnishing',
            field=models.CharField(blank=True, choices=[('furnished', 'Fully Furnished'), ('semi_furnished', 'Semi Furnished'), ('unfurnished', 'Unfurnished')], max_length=20, null=True, verbose_name='Furnishing'),
        ),
        migrations.AlterField(
            model_name='property',
            name='inquiry_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Inquiry Count'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Premium'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='property',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Landmark'),
        ),
        migrations.AlterField(
            model_name='property',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('lease', 'For Lease'), ('pg', 'PG/Co-Living')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='locality',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Locality/Area'),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='property',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='Parking Spaces'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pincode',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_negotiable',
            field=models.BooleanField(default=False, verbose_name='Price Negotiable'),
        ),
        migrations.AlterField(
            model_name='property',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published At'),
        ),
        migrations.AlterField(
            model_name='property',
            name='ref_id',
            field=models.CharField(default=2, editable=False, max_length=20, unique=True, verbose_name='Reference ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='rera_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RERA Number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rera_registered',
            field=models.BooleanField(default=False, verbose_name='RERA Registered'),
        ),
        migrations.AlterField(
            model_name='property',
            name='security_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Security Deposit'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(max_length=100, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('active', 'Active'), ('inactive', 'Inactive'), ('sold', 'Sold'), ('rented', 'Rented'), ('expired', 'Expired'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='subcategory',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='estate_app.propertysubcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Property Title'),
        ),
        migrations.AlterField(
            model_name='property',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='View Count'),
        ),
        migrations.AlterField(
            model_name='propertycategory',
            name='description',
            field=models.TextField(blank=True, default=2, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertycategory',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='propertycategory',
            name='icon',
            field=models.CharField(blank=True, default=3, max_length=50, verbose_name='Icon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertycategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='propertycategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='propertycategory',
            name='property_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('land', 'Plots/Land'), ('agricultural', 'Agricultural'), ('pg_co-living', 'PG/Co-Living')], max_length=20, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='propertycategory',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='properties/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Primary Image'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='estate_app.property'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='properties/thumbnails/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='propertyinquiry',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='propertyinquiry',
            name='phone',
            field=models.CharField(max_length=17, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='propertyinquiry',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries_responded', to=settings.AUTH_USER_MODEL, verbose_name='responded by'),
        ),
        migrations.AlterField(
            model_name='propertyinquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('scheduled', 'Site Visit Scheduled'), ('negotiation', 'Under Negotiation'), ('closed_won', 'Closed - Won'), ('closed_lost', 'Closed - Lost'), ('spam', 'Spam')], default='new', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='propertyinquiry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries_made', to=settings.AUTH_USER_MODEL, verbose_name='inquirer'),
        ),
        migrations.AlterField(
            model_name='propertysubcategory',
            name='description',
            field=models.TextField(blank=True, default=3, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertysubcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='propertysubcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Subcategory Name'),
        ),
        migrations.AlterField(
            model_name='propertysubcategory',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterUniqueTogether(
            name='propertysubcategory',
            unique_together={('category', 'name')},
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['category', 'subcategory'], name='estate_app__categor_60df2b_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_active', 'status'], name='estate_app__is_acti_ec63ab_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['listing_type'], name='estate_app__listing_89b0e3_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyinquiry',
            index=models.Index(fields=['status', 'priority'], name='core_proper_status_20fd69_idx'),
        ),
        migrations.AlterModelTable(
            name='amenity',
            table=None,
        ),
        migrations.AlterModelTable(
            name='property',
            table=None,
        ),
        migrations.AlterModelTable(
            name='propertycategory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='propertyimage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='propertysubcategory',
            table=None,
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='estate_app.property'),
        ),
        migrations.RemoveField(
            model_name='property',
            name='area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='brochure',
        ),
        migrations.RemoveField(
            model_name='property',
            name='click_through_rate',
        ),
        migrations.RemoveField(
            model_name='property',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='property',
            name='floor_plan',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_sold_rented',
        ),
        migrations.RemoveField(
            model_name='property',
            name='performance_score',
        ),
        migrations.RemoveField(
            model_name='property',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='property',
            name='virtual_tour',
        ),
        migrations.RemoveField(
            model_name='property',
            name='year_built',
        ),
        migrations.RemoveField(
            model_name='propertycategory',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='propertycategory',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='propertyinquiry',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='propertyinquiry',
            name='inquiry_type',
        ),
        migrations.RemoveField(
            model_name='propertyinquiry',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='propertyinquiry',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='propertyinquiry',
            name='preferred_date',
        ),
        migrations.RemoveField(
            model_name='propertyinquiry',
            name='preferred_time',
        ),
    ]
