# Generated by Django 6.0 on 2026-02-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0002_property_locality_alter_property_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='verification attempts'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_locked_until',
            field=models.DateTimeField(blank=True, help_text='Until when the verification is locked due to too many attempts', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='E8610028', max_length=20, unique=True, verbose_name='property ID'),
        ),
    ]
