# Generated by Django 6.0 on 2026-02-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0003_customuser_verification_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verification_attempts',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_locked_until',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='C186FF13', max_length=20, unique=True, verbose_name='property ID'),
        ),
    ]
