# Generated by Django 6.0 on 2026-02-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0004_remove_customuser_verification_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinquiry',
            name='follow_ups',
            field=models.JSONField(blank=True, default=list, verbose_name='follow ups'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='last_followup_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last followup at'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='D530EC12', max_length=20, unique=True, verbose_name='property ID'),
        ),
    ]
